In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

This folder just contains the data analysis, and extra steps taken before the final result. Examing the data, and making necessary changes

In [ ]:
#Figure 2 Exploration:
#Check the genres for next exploration
df["listed_in"].head(10)

0                                        Documentaries
1      International TV Shows, TV Dramas, TV Mysteries
2    Crime TV Shows, International TV Shows, TV Act...
3                               Docuseries, Reality TV
4    International TV Shows, Romantic TV Shows, TV ...
5                   TV Dramas, TV Horror, TV Mysteries
6                             Children & Family Movies
7     Dramas, Independent Movies, International Movies
8                         British TV Shows, Reality TV
9                                     Comedies, Dramas
Name: listed_in, dtype: object

In [ ]:
#Fig 2
#Separating and counting the genres
genres = []

for item in df["listed_in"]:
  genre_list = item.split(",")

  for genre in genre_list:
    genres.append(genre.strip())

genre_counts = pd.Series(genres).value_counts()
genre_counts.head(10)

International Movies        2752
Dramas                      2427
Comedies                    1674
International TV Shows      1351
Documentaries                869
Action & Adventure           859
TV Dramas                    763
Independent Movies           756
Children & Family Movies     641
Romantic Movies              616
Name: count, dtype: int64

In [ ]:
#Figure 3 Data Analysis
#Country exploration
df["country"].head(10)

0                                        United States
1                                         South Africa
2                                                  NaN
3                                                  NaN
4                                                India
5                                                  NaN
6                                                  NaN
7    United States, Ghana, Burkina Faso, United Kin...
8                                       United Kingdom
9                                        United States
Name: country, dtype: object

In [ ]:
#Fig 3
#Separate and count the countries
countries = []

for item in df["country"]:
  if pd.notna(item):
    country_list = item.split(",")

    for country in country_list:
      countries.append(country.strip())

country_counts = pd.Series(countries).value_counts()
country_counts.head(10)

United States     3690
India             1046
United Kingdom     806
Canada             445
France             393
Japan              318
Spain              232
South Korea        231
Germany            226
Mexico             169
Name: count, dtype: int64

NOT including the final figure result in this folder

In [ ]:
#Figure 4:
#Explore the duration column
df["duration"].head(15)

0        90 min
1     2 Seasons
2      1 Season
3      1 Season
4     2 Seasons
5      1 Season
6        91 min
7       125 min
8     9 Seasons
9       104 min
10     1 Season
11     1 Season
12      127 min
13       91 min
14     1 Season
Name: duration, dtype: object

In [ ]:
#Fig 4
#Filtering Movies from TV Shows
movies = df[df["type"] == "Movie"]
movies [["title", "duration"]].head(10)

                                                title duration
0                                Dick Johnson Is Dead   90 min
6                    My Little Pony: A New Generation   91 min
7                                             Sankofa  125 min
9                                        The Starling  104 min
12                                       Je Suis Karl  127 min
13                   Confessions of an Invisible Girl   91 min
16  Europe's Most Dangerous Man: Otto Skorzeny in ...   67 min
18                                          Intrusion   94 min
22                                    Avvai Shanmughi  161 min
23       Go! Go! Cory Carson: Chrissy Takes the Wheel   61 min

In [ ]:
#Conversion of movie durations in numbers
movies = movies.copy()
movies["duration_minutes"] = movies["duration"].str.replace(" min", "")
movies["duration_minutes"] = pd.to_numeric(movies["duration_minutes"], errors = "coerce")
movies[["title", "duration_minutes"]].head(10)

                                                title  duration_minutes
0                                Dick Johnson Is Dead              90.0
6                    My Little Pony: A New Generation              91.0
7                                             Sankofa             125.0
9                                        The Starling             104.0
12                                       Je Suis Karl             127.0
13                   Confessions of an Invisible Girl              91.0
16  Europe's Most Dangerous Man: Otto Skorzeny in ...              67.0
18                                          Intrusion              94.0
22                                    Avvai Shanmughi             161.0
23       Go! Go! Cory Carson: Chrissy Takes the Wheel              61.0